# Generated by Django 2.0.7 on 2020-06-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
