# Generated by Django 2.0.7 on 2020-06-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200610_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
