# Generated by Django 2.0.7 on 2020-07-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200707_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorrequest',
            name='request_from',
        ),
        migrations.RemoveField(
            model_name='mentorrequest',
            name='request_to',
        ),
        migrations.AlterField(
            model_name='profile',
            name='requests',
            field=models.ManyToManyField(to='mentors.MentorRequest'),
        ),
        migrations.DeleteModel(
            name='MentorRequest',
        ),
    ]
