# Generated by Django 2.0.7 on 2020-06-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Random Question Title', max_length=120),
            preserve_default=False,
        ),
    ]
