# Generated by Django 2.0.7 on 2020-06-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('forum', '0008_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='communities',
            field=models.ManyToManyField(to='communities.Community'),
        ),
    ]
